version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resumo_academico_web
    restart: unless-stopped
    
    environment:
      SECRET_KEY: ${SECRET_KEY:-django-insecure-9!n#rv)tdbj5ye2$5(#if!aegl2c+fvmakkr3a924sccmwumj9}
      DEBUG: ${DEBUG:-True}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0,web,72.61.54.207}
      
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      
      TZ: ${TZ:-America/Sao_Paulo}
    
    volumes:
      # - .:/app  ‚Üê REMOVA ESTA LINHA
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    
    ports:
      - "8001:8000"
    
    networks:
      - global_network
    
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  static_volume:
    driver: local
    name: resumo_academico_static
  
  media_volume:
    driver: local
    name: resumo_academico_media

networks:
  global_network:
    external: true